### ISSUE TITLE
videoplay seektoTime不能保存之前的播放状态

### ISSUE THREAD

**Issue by xuty** [upyun/ios-short-video#3]
在播放暂停状态，拖动进度条调用seekto 之后不能继续暂停而是播放视频，强制暂停也不起作用
UPAVPlayerStatus oldPlayerStatus = _player.playerStatus;
 [_player seekToTime:slider_.value];
 if ( UPAVPlayerStatusPause == oldPlayerStatus ) {
      [_player pause];//不能实现暂停
  }

**Comment by linKnowEasy** [comment]
嗯. 目前是这样的
播放器 拖动之后. 会加载并自动播放.
