### ISSUE TITLE
ios9系统下直播之下播放崩溃

### ISSUE THREAD

**Issue by Sky-star** [upyun/ios-short-video#4]
http://play.shangzhibo.tv/onelive/MTA2NzcyLTQ4NTA4NjYtTXMtajhLXzN3bw==.m3u8
这个地址在ios9下播放崩溃，其他系统并没有这个问题

**Comment by linKnowEasy** [comment]
方便发一下崩溃 log 嘛.
另: 可能提错 Issue 了, 这是短视频 SDK 地址

**Comment by Sky-star** [comment]
![image](https://user-images.githubusercontent.com/6882646/51731456-f8644100-20b5-11e9-96f8-d9b23a5dba5a.png)

这个我在其余系统下使用并没有问题。 是直播流。

**Comment by linKnowEasy** [comment]
目前我们身边没有 iOS 9 以下的测试设备.  具体的测试设备与手机型号方便提供一下嘛

能否试试 https://github.com/upyun/ios-live-sdk  这个播放器能不能正常播放
ps: 短视频播放器是基于直播播放器部分代码调整的

**Comment by Sky-star** [comment]
iPhone 6 版本:9.3.3 型号: NG472CH/A
那个SDK我也试过了 也不行。

**Comment by linKnowEasy** [comment]
谢谢提供信息, 我们先排查一下,

**Comment by saibogoo** [comment]
iOS13报错有查看吗
