### ISSUE TITLE
播放视频画面拉伸变形，应该设置哪个参数？

### ISSUE THREAD

**Issue by qingwu126** [upyun/ios-short-video#6]

**Comment by linKnowEasy** [comment]
有相关的截图嘛

**Comment by qingwu126** [comment]
有

**Comment by qingwu126** [comment]
在demo里播放也是拉伸变形的，

**Comment by linKnowEasy** [comment]
demo 中播放并没有出现拉伸变形的情况. 能否提供截图
@qingwu126

**Comment by qingwu126** [comment]
<img width="953" alt="WechatIMG1135" src="https://user-images.githubusercontent.com/10303151/58679636-034a1d80-8397-11e9-8366-4b21b467b81b.png">

**Comment by qingwu126** [comment]
![IMG_2578](https://user-images.githubusercontent.com/10303151/58679693-40161480-8397-11e9-936b-870e4b1a76d4.PNG)

**Comment by linKnowEasy** [comment]
视频源地址有嘛. 我怀疑是 视频的 rotate 属性可能没处理好

**Comment by qingwu126** [comment]
播放器是根据视频的 rotate 属性设置播放画面的吗？

**Comment by linKnowEasy** [comment]
目前只对 rotate 90 和 270  且在竖屏的情况下 做了处理

**Comment by linKnowEasy** [comment]
如果不需要这个处理. 可以回退 commit 到之前的版本
![image](https://user-images.githubusercontent.com/8413135/58680301-cfbcc280-8399-11e9-87ee-271760b1d747.png)

**Comment by qingwu126** [comment]
视频地址：http://videosss.test.upcdn.net/development_cba83e48-e5cd-43f3-a62b-ea5530960f9e.mp4

**Comment by linKnowEasy** [comment]
视频的 rotate 属性与 视频长宽之间没有协调好.
后续会更新这个 bug. 如果着急的话. 建议 回滚 commit ,然后测试一下
