### ISSUE TITLE
iOS13 播放器释放报错

### ISSUE THREAD

**Issue by saibogoo** [upyun/ios-short-video#7]
[reports] Main Thread Checker: UI API called on a background thread: -[UIApplication setIdleTimerDisabled:]
PID: 1166, TID: 242079, Thread name: (none), Queue name: UPAVPlayer_frameReadQueue, QoS: 0

**Comment by linKnowEasy** [comment]
@benhot  已经修复. 
更新 UPLiveSDK.framework 即可
